### ISSUE TITLE
cant create island

### ISSUE THREAD

**Issue by XXX10Tacles** [SavageLabs/SavageSkyblock-OLD#1]
spigot version: [20:20:00 INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-7fc66b2 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[20:20:00 INFO]: Checking version, please wait...
[20:20:01 INFO]: You are running the latest version

plugin version: 1.9.1-b

when i am tryng to create island: 

`[20:18:41 INFO]: AvTo_ issued server command: /is create
[20:18:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin EpicSkyblock v1.9.1-b
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/LocalWorld
        at com.peaches.epicskyblock.IslandManager.createIsland(IslandManager.java:63) ~[?:?]
        at com.peaches.epicskyblock.Command.onCommand(Command.java:327) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.LocalWorld
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at com.peaches.epicskyblock.IslandManager.createIsland(IslandManager.java:63) ~[?:?]
        at com.peaches.epicskyblock.Command.onCommand(Command.java:327) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        ... 15 more`

**Comment by PeachesMLG** [comment]
This has been fixed in 1.9.2-b

**Comment by Perkaholics** [comment]
I still have this issue even when running latest version of the plugin. I still can’t figure it out.
